/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package OnlineMall;

import javax.swing.JOptionPane;
import javax.swing.*;
import java.util.*;
import java.io.*;
/**
 *
 * @author hp
 */
public class CreateNewCustomerAccount extends javax.swing.JFrame {

   
      
    
     ArrayList <CustomerAccount> Customers;
    /**
     * Creates new form CreateNewCustomerAccount
     */
    public CreateNewCustomerAccount() {
        
        initComponents();
       Customers = new ArrayList<CustomerAccount>();

         
        
        populateArrayList3();
        
        
    }

      public void populateArrayList3()
    {
        try
        {
        
            FileInputStream file = new FileInputStream("src\\DataBase\\Customers.dat");
            ObjectInputStream inputFile = new ObjectInputStream(file);
        boolean endOfFile = false;
        
        while (!endOfFile){
            
            try 
            {
              Customers.add((CustomerAccount) inputFile.readObject());
                
            }
            catch (EOFException e)
            {
                endOfFile = true;
            }
            catch (Exception f)
            {
             JOptionPane.showMessageDialog(null, f.getMessage());
            }
        }
        
        inputFile.close();
        }
        catch (IOException e){
            
            JOptionPane.showMessageDialog(null, e.getMessage());
            
        }
        
        
    }
    
    public void saveCustomerToFile(){
         
            try 
            {
              FileOutputStream file = new FileOutputStream("src\\DataBase\\Customers.dat");
              ObjectOutputStream outputFile = new ObjectOutputStream(file);
                
              
              for (int i=0; i<Customers.size(); i++){
                  
                  outputFile.writeObject(Customers.get(i));
                  
              }
              
              outputFile.close();
              JOptionPane.showMessageDialog(null, "The Account was succefully created, please log in from the main interface");
             
            }
        
         catch (IOException e){
            
            JOptionPane.showMessageDialog(null, e.getMessage());
            
        }
        
    }
  
    
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        UserNameText = new javax.swing.JTextField();
        EmailAddressText = new javax.swing.JTextField();
        PhoneNumberText = new javax.swing.JTextField();
        CityText = new javax.swing.JTextField();
        TownText = new javax.swing.JTextField();
        DistrictText = new javax.swing.JTextField();
        StreetText = new javax.swing.JTextField();
        HomeText = new javax.swing.JTextField();
        UserName = new javax.swing.JLabel();
        EmailAddress = new javax.swing.JLabel();
        PhoneNumber = new javax.swing.JLabel();
        City = new javax.swing.JLabel();
        Town = new javax.swing.JLabel();
        District = new javax.swing.JLabel();
        street = new javax.swing.JLabel();
        HomeAddress = new javax.swing.JLabel();
        CreditCardNumber = new javax.swing.JLabel();
        CreditCardText = new javax.swing.JTextField();
        FieldsMarked = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        PasswordText = new javax.swing.JPasswordField();
        ConfirmPasswordText = new javax.swing.JPasswordField();
        Password = new javax.swing.JLabel();
        ConfirmPassword = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Create Account");
        setMinimumSize(new java.awt.Dimension(540, 590));
        getContentPane().setLayout(null);

        UserNameText.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        UserNameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserNameTextActionPerformed(evt);
            }
        });
        getContentPane().add(UserNameText);
        UserNameText.setBounds(140, 160, 337, 19);

        EmailAddressText.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        EmailAddressText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmailAddressTextActionPerformed(evt);
            }
        });
        getContentPane().add(EmailAddressText);
        EmailAddressText.setBounds(140, 250, 337, 19);

        PhoneNumberText.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        PhoneNumberText.setText("+02");
        PhoneNumberText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PhoneNumberTextActionPerformed(evt);
            }
        });
        getContentPane().add(PhoneNumberText);
        PhoneNumberText.setBounds(140, 280, 337, 19);

        CityText.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        CityText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CityTextActionPerformed(evt);
            }
        });
        getContentPane().add(CityText);
        CityText.setBounds(140, 320, 335, 19);

        TownText.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        TownText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TownTextActionPerformed(evt);
            }
        });
        getContentPane().add(TownText);
        TownText.setBounds(140, 360, 335, 19);

        DistrictText.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        DistrictText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DistrictTextActionPerformed(evt);
            }
        });
        getContentPane().add(DistrictText);
        DistrictText.setBounds(140, 390, 335, 19);

        StreetText.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        StreetText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StreetTextActionPerformed(evt);
            }
        });
        getContentPane().add(StreetText);
        StreetText.setBounds(140, 430, 335, 19);

        HomeText.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        HomeText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeTextActionPerformed(evt);
            }
        });
        getContentPane().add(HomeText);
        HomeText.setBounds(140, 460, 333, 19);

        UserName.setFont(new java.awt.Font("Serif", 2, 12)); // NOI18N
        UserName.setText("UserName:");
        getContentPane().add(UserName);
        UserName.setBounds(50, 160, 70, 17);

        EmailAddress.setFont(new java.awt.Font("Serif", 2, 12)); // NOI18N
        EmailAddress.setText("Email Adrress:");
        getContentPane().add(EmailAddress);
        EmailAddress.setBounds(30, 250, 90, 17);

        PhoneNumber.setFont(new java.awt.Font("Serif", 2, 12)); // NOI18N
        PhoneNumber.setText("Phone Number:");
        getContentPane().add(PhoneNumber);
        PhoneNumber.setBounds(20, 280, 90, 17);

        City.setFont(new java.awt.Font("Serif", 2, 12)); // NOI18N
        City.setText("City:");
        getContentPane().add(City);
        City.setBounds(70, 320, 40, 17);

        Town.setFont(new java.awt.Font("Serif", 2, 12)); // NOI18N
        Town.setText("Town*:");
        getContentPane().add(Town);
        Town.setBounds(60, 360, 50, 17);

        District.setFont(new java.awt.Font("Serif", 2, 12)); // NOI18N
        District.setText("District:");
        getContentPane().add(District);
        District.setBounds(57, 400, 50, 17);

        street.setFont(new java.awt.Font("Serif", 2, 12)); // NOI18N
        street.setText("Street Address:");
        getContentPane().add(street);
        street.setBounds(26, 430, 90, 17);

        HomeAddress.setFont(new java.awt.Font("Serif", 2, 12)); // NOI18N
        HomeAddress.setText("Home Address:");
        getContentPane().add(HomeAddress);
        HomeAddress.setBounds(26, 460, 90, 17);

        CreditCardNumber.setFont(new java.awt.Font("Serif", 2, 12)); // NOI18N
        CreditCardNumber.setText("Credit-Card Number*:");
        getContentPane().add(CreditCardNumber);
        CreditCardNumber.setBounds(4, 500, 130, 17);

        CreditCardText.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        CreditCardText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreditCardTextActionPerformed(evt);
            }
        });
        getContentPane().add(CreditCardText);
        CreditCardText.setBounds(140, 500, 333, 19);

        FieldsMarked.setText("fields that are marked * are optional");
        getContentPane().add(FieldsMarked);
        FieldsMarked.setBounds(151, 137, 290, 14);

        jButton1.setText("Create Account");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(200, 530, 130, 40);

        PasswordText.setText("jPasswordField1");
        getContentPane().add(PasswordText);
        PasswordText.setBounds(140, 190, 337, 20);

        ConfirmPasswordText.setText("jPasswordField1");
        getContentPane().add(ConfirmPasswordText);
        ConfirmPasswordText.setBounds(140, 220, 337, 20);

        Password.setFont(new java.awt.Font("Serif", 2, 12)); // NOI18N
        Password.setText("Password:");
        getContentPane().add(Password);
        Password.setBounds(50, 190, 70, 17);

        ConfirmPassword.setFont(new java.awt.Font("Serif", 2, 12)); // NOI18N
        ConfirmPassword.setText("Confirm password: ");
        getContentPane().add(ConfirmPassword);
        ConfirmPassword.setBounds(10, 220, 110, 17);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UserNameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserNameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UserNameTextActionPerformed

    private void EmailAddressTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailAddressTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmailAddressTextActionPerformed

    private void PhoneNumberTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PhoneNumberTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PhoneNumberTextActionPerformed

    private void CityTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CityTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CityTextActionPerformed

    private void TownTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TownTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TownTextActionPerformed

    private void DistrictTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DistrictTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DistrictTextActionPerformed

    private void StreetTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StreetTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StreetTextActionPerformed

    private void HomeTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HomeTextActionPerformed

    private void CreditCardTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreditCardTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CreditCardTextActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
   
        if (HomeText.getText().isEmpty() ||StreetText.getText().isEmpty() ||
                DistrictText.getText().isEmpty()  ||CityText.getText().isEmpty() ||
                PhoneNumberText.getText().isEmpty() ||EmailAddressText.getText().isEmpty() ||UserNameText.getText().isEmpty()){
            
             JOptionPane.showMessageDialog(null, "One of the Required fields is empty please fill it");
            
        }else{
        
        
            
       
        String Name = UserNameText.getText().trim();
        String Password = PasswordText.getText();
        String Email = EmailAddressText.getText();
        String phoneNumber = PhoneNumberText.getText();
        String city =  CityText.getText();
        String town = TownText.getText();
        String district = DistrictText.getText();
        String StreetAddress = StreetText.getText();        
        String PlaceAddress = HomeText.getText();
        String Creditcard = CreditCardText.getText();
     
      
            
       
        
       
        CustomerAccount Customer =new CustomerAccount(Name,Password,Email,phoneNumber,city,town,district,StreetAddress,PlaceAddress,Creditcard);
        
        Customers.add(Customer);
        saveCustomerToFile();
        
        
        }         
       
    
       
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateNewCustomerAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateNewCustomerAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateNewCustomerAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateNewCustomerAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateNewCustomerAccount().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel City;
    private javax.swing.JTextField CityText;
    private javax.swing.JLabel ConfirmPassword;
    private javax.swing.JPasswordField ConfirmPasswordText;
    private javax.swing.JLabel CreditCardNumber;
    private javax.swing.JTextField CreditCardText;
    private javax.swing.JLabel District;
    private javax.swing.JTextField DistrictText;
    private javax.swing.JLabel EmailAddress;
    private javax.swing.JTextField EmailAddressText;
    private javax.swing.JLabel FieldsMarked;
    private javax.swing.JLabel HomeAddress;
    private javax.swing.JTextField HomeText;
    private javax.swing.JLabel Password;
    private javax.swing.JPasswordField PasswordText;
    private javax.swing.JLabel PhoneNumber;
    private javax.swing.JTextField PhoneNumberText;
    private javax.swing.JTextField StreetText;
    private javax.swing.JLabel Town;
    private javax.swing.JTextField TownText;
    private javax.swing.JLabel UserName;
    private javax.swing.JTextField UserNameText;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel street;
    // End of variables declaration//GEN-END:variables
}
