/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package OnlineMall;
import java.awt.Desktop;  
import java.io.*;
import java.io.FileWriter;  
import java.util.ArrayList;
import javax.swing.JOptionPane;
/**
 *
 * @author flossycat
 */
public class ManageRequests extends javax.swing.JFrame {
  ArrayList <Applications> Applications;
    /**
     * Creates new form ManageRequests
     */
    public ManageRequests() {
         Applications = new ArrayList<Applications>();
        initComponents();
        populateArrayList2();
    }
 public void populateArrayList2()
    {
        try
        {
        
            FileInputStream file = new FileInputStream("src\\DataBase\\Applications.dat");
            ObjectInputStream inputFile = new ObjectInputStream(file);
        boolean EndOfFile = false;
        
        while (!EndOfFile){
            
            try 
            {
              Applications.add((Applications) inputFile.readObject());
                
            }
            catch (EOFException e)
            {
                EndOfFile = true;
            }
            catch (Exception d)
            {
             JOptionPane.showMessageDialog(null, d.getMessage());
            }
        }
        
        inputFile.close();
        }
        catch (IOException l){
            
            JOptionPane.showMessageDialog(null, l.getMessage());
            
        }
        
        
    }
 
 
 
  public void saveApplicationsToFile(){
         
            try 
            {
              FileOutputStream file = new FileOutputStream("src\\DataBase\\Applications.dat");
              ObjectOutputStream outputFile = new ObjectOutputStream(file);
                
              
              for (int i=0; i<Applications.size(); i++){
                  
                  outputFile.writeObject(Applications.get(i));
                  
              }
              
              outputFile.close();
              JOptionPane.showMessageDialog(null, "The Application status was succefully saved");
             
            
             
            }
        
         catch (IOException e){
            
            JOptionPane.showMessageDialog(null, e.getMessage());
            
        }
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        InsertText = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(260, 320));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("ShowRequests");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 172, 186, -1));

        jButton2.setText("Approve");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 239, 89, -1));

        jButton3.setText("DisApprove");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 239, -1, -1));

        InsertText.setForeground(new java.awt.Color(204, 204, 204));
        InsertText.setText("Insert Application Number here");
        InsertText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertTextActionPerformed(evt);
            }
        });
        getContentPane().add(InsertText, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 213, 186, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OnlineMall/logo.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try  
{  

File f = new File("src\\DataBase\\ManageShopRequests.txt");   
if(!Desktop.isDesktopSupported())
{  
System.out.println("aint working");  
return;  
}  
Desktop desktop = Desktop.getDesktop();  
if(f.exists())        
desktop.open(f);              
}  
catch(Exception e)  
{  
e.printStackTrace();  
}  
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        
        
        
        
         
       
        String Applicationstatus = "Approved";
        String ApplicationNumber =  InsertText.getText().trim();
        
     
      
            
       
        
       
        Applications application =new Applications(ApplicationNumber,Applicationstatus);
        
        Applications.add(application);
        saveApplicationsToFile();
         
        
        try
        {
        
            FileInputStream file = new FileInputStream("src\\DataBase\\Applications.dat");
            ObjectInputStream inputFile = new ObjectInputStream(file);
        
      FileWriter fw3= new FileWriter("src\\DataBase\\ApplicationStatus.txt",true);  
        
       for (int i=0;i<Applications.size();i++){
           
            try 
            {
              
                    fw3.write( "\n" + Applications.get(i).ApplicationNumber + " " + Applications.get(i).Applicationstatus+ "\n");
                  
            }
            catch (Exception f)
            {
             JOptionPane.showMessageDialog(null, f.getMessage());
            }
          
        }
        fw3.close();
        inputFile.close();
        }
        catch (IOException e){
            
            JOptionPane.showMessageDialog(null, e.getMessage());
            
        }
    
        
        
         
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
    
        String Applicationstatus = "DisApproved";
        String ApplicationNumber =  InsertText.getText().trim();
        
     
      
            
       
        
       
        Applications application =new Applications(ApplicationNumber,Applicationstatus);
        
        Applications.add(application);
        saveApplicationsToFile();
        
          try
        {
        
            FileInputStream file = new FileInputStream("src\\DataBase\\Applications.dat");
            ObjectInputStream inputFile = new ObjectInputStream(file);
        
      FileWriter fw3= new FileWriter("src\\DataBase\\ApplicationStatus.txt",true);  
        
       for (int i=0;i<Applications.size();i++){
           
            try 
            {
              
                    fw3.write( "\n" + Applications.get(i).ApplicationNumber + " " + Applications.get(i).Applicationstatus+ "\n");
                  
            }
            catch (Exception f)
            {
             JOptionPane.showMessageDialog(null, f.getMessage());
            }
          
        }
        fw3.close();
        inputFile.close();
        }
        catch (IOException e){
            
            JOptionPane.showMessageDialog(null, e.getMessage());
            
        }
        
         
    }//GEN-LAST:event_jButton3ActionPerformed

    private void InsertTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InsertTextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageRequests.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageRequests.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageRequests.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageRequests.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageRequests().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField InsertText;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
